system:
    default:
        css:
            files:
                - %platformui_search.css_dir%/views/search.css
                - %platformui_search.css_dir%/theme/views/search.css
                - %platformui_search.css_dir%/theme/views/actions/button.css